image: gitpod/workspace-full-vnc

tasks:
  - name: Setup Android Studio
    init: |
      # Installer les dépendances nécessaires
      sudo apt update && sudo apt install -y libc6 libncurses5 libstdc++6 zlib1g libbz2-1.0

      # Télécharger et installer Android Studio
      wget -q https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.20/android-studio-2023.2.1.20-linux.tar.gz
      tar -xvzf android-studio-*.tar.gz

      # Démarrer VNC
      vncserver :1 -geometry 1280x720 -localhost no

      # Lancer Android Studio
      ./android-studio/bin/studio.sh &
      
ports:
  - port: 5901
    onOpen: open-preview
    visibility: public
