image: gitpod/workspace-full-vnc
tasks:
  - init: |
      wget -q https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.2.1.20/android-studio-2023.2.1.20-linux.tar.gz &&
      tar -xvzf android-studio-*.tar.gz &&
      ./android-studio/bin/studio.sh
ports:
  - port: 5901
    onOpen: open-preview
